Merge Testing into Main
virtual-labs/exp-structures-iiith pull request #6
Opened 2023-11-08 09:59 UTC by bhavberi

2023-11-09 07:40 UTC, raj-vlabs requested changes
1. Remove all commented out code.
2. Check the questions for grammar and consistency.

2023-11-09 07:40 UTC, raj-vlabs commented on experiment/aim.md
> +When working with data in programming, you often encounter variables of specific data types like int or char, which can store only a single element of that data type. However, the real world is rarel
_'What if you need to manage a collection of related elements, each with its own data type? Arrays offer a solution'_
Arrays do not support different data types in one collection

2023-11-09 07:40 UTC, raj-vlabs commented on experiment/aim.md
> +With this lab, you will gets hands-on and try:
It's an experiment not a lab

2023-11-09 07:40 UTC, raj-vlabs commented on experiment/posttest.json
> +            "question": "2. Can arrays be a part of the structure?",
Grammatically correct the sentence.
An Array can be a part of a Structure

2023-11-09 07:40 UTC, raj-vlabs commented on experiment/simulation/index.html
> +			<!-- <div class="mdl-cell mdl-cell--6-col mdl-cell--8-col-tablet mdl-cell--4-col-phone">
Please remove all commented  out code

2023-11-12 17:27 UTC, bhavberi commented on experiment/posttest.json
> +            "question": "2. Can arrays be a part of the structure?",
I didn't create these questions; only a few at the end were made by me. I didn't check at that time, but I have changed it now.

2023-11-20 13:09 UTC, raj-vlabs approved these changes

2023-11-20 13:09 UTC, raj-vlabs commented on experiment/simulation/js/main.js
> +    stateOfExeplation: 0, // shows state of exeplation.
What is exeplation? Is it explanation misspelt?

2023-11-20 13:10 UTC, merged